apps/inicio/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detalle/(?P<question_id>[0-9]+)/$', views.modificar, name='modificar'),
    url(r'^nuevo/$', views.nuevo, name='nuevo'),
    url(r'^eliminar/(?P<question_id>[0-9]+)/$', views.eliminar, name='eliminar'),
]

practica18/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from apps.inicio import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'practica18.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.inicio, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^inicio/', include('apps.inicio.urls')),
]

apps/inicio/models.py
from django.db import models

class alumno(models.Model):
    nombres=models.CharField(max_length=300)
    apellp=models.CharField(max_length=50)
    apellm=models.CharField(max_length=50)
    edad=models.IntegerField(default=0)
    carrera=models.CharField(max_length=100)

    def __unicode__(self):
        return self.apellp+" "+self.apellm+" "+self.nombres

apps/inicio/forms.py
from django import forms

class nuevoAlumno(forms.Form):
    nombres=forms.CharField(label='Nombre',widget=forms.TextInput())
    apellidop=forms.CharField(label='Ape Paterno',widget=forms.TextInput())
    apellidom=forms.CharField(label='Ape Materno',widget=forms.TextInput())
    edad=forms.IntegerField(label='Edad',widget=forms.TextInput())
    carrera=forms.CharField(label='Carrera',widget=forms.TextInput())

apps/inicio/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from .models import alumno
from .forms import nuevoAlumno

def index(request):
    latest_question_list = alumno.objects.all()
    template = loader.get_template('index.html')
    context = RequestContext(request, {
        'alumnos': latest_question_list,
    })
    return HttpResponse(template.render(context))

def nuevo(request):
    if request.method=='GET':
        formulario=nuevoAlumno()
        template = loader.get_template('nuevo.html')
        context = RequestContext(request, {
            'form': formulario,
        })
        return HttpResponse(template.render(context))
    else:
        nombres=""
        apellp=""
        apellm=""
        edad=""
        carrera=""
        formulario=nuevoAlumno(request.POST)
        if formulario.is_valid():
            nombres=formulario.cleaned_data['nombres']
            apellp=formulario.cleaned_data['apellidop']
            apellm=formulario.cleaned_data['apellidom']
            edad=formulario.cleaned_data['edad']
            carrera=formulario.cleaned_data['carrera']
            alum=alumno()
            alum.nombres=nombres
            alum.apellp=apellp
            alum.apellm=apellm
            alum.edad=edad
            alum.carrera=carrera
            alum.save()

        return HttpResponseRedirect('/inicio/')


def modificar(request,question_id):
    if request.method=='GET':

        alumnosss=alumno.objects.get(id=question_id)
        template = loader.get_template('modificar.html')
        context = RequestContext(request, {
            'alumno': alumnosss,
        })
        return HttpResponse(template.render(context))
    else:
        nombres=""
        apellp=""
        apellm=""
        edad=""
        carrera=""
        formulario=nuevoAlumno(request.POST)
        if formulario.is_valid():
            nombres=formulario.cleaned_data['nombres']
            apellp=formulario.cleaned_data['apellidop']
            apellm=formulario.cleaned_data['apellidom']
            edad=formulario.cleaned_data['edad']
            carrera=formulario.cleaned_data['carrera']
            alum=alumno.objects.get(id=question_id)
            alum.nombres=nombres
            alum.apellp=apellp
            alum.apellm=apellm
            alum.edad=edad
            alum.carrera=carrera
            alum.save()

        return HttpResponseRedirect('/inicio/')

def inicio(request):
    return HttpResponseRedirect('/inicio/')

def eliminar(request,question_id):
    alu = alumno.objects.get(id=question_id)
    alu.delete()
    return HttpResponseRedirect('/inicio/')

apps/inicio/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Principal</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'icono.png' %}"/>
    <link rel="icon" type="image/png" href="{% static 'icono.png' %}" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}" />
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Latest compiled and minified CSS -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"-->

    <!-- Optional theme -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css"-->

    <!-- Latest compiled and minified JavaScript -->
    <!--script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script-->
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Inicio</span>

              </button>
              <a class="navbar-brand" href="/">Alumnos</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Inicio</a></li>
                <li><a href="#">Acerca</a></li>
                <li><a href="#">Contacto</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
        <div class="jumbotron">
            <h2>Alumnos</h2>
        </div>
    <ul>

        <a class="btn btn-primary" href="nuevo/">Nuevo</a>
        <br>
        <br>
        {% if alumnos %}
            {% for alumno in alumnos %}
                <p><a href="detalle/{{ alumno.id }}/"  class="button">{{ alumno.nombres }} -
                    {{ alumno.apellp }} - {{ alumno.apellm }} - {{ alumno.edad }} - {{ alumno.carrera }}</a>
                </p>
                <a  class="btn btn-xs btn-primary" href="eliminar/{{alumno.id}}/">Eliminar</a>
                <br><br>
            {% endfor %}


        {% else %}
            <p>No hay Alumnos</p>
        {% endif %}

    </ul>
    </div>

    <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script-->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!--script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script-->
    <!--script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script-->

</body>
</html>

apps/inicio/templates/modificar.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Modificar</title>
    <!--link rel="shortcut icon" href="LC_Icono_01_128.png" />
    <link rel="icon" type="image/png" href="LC_Icono_01_128.png" />
    <link rel="icon" type="image/gif" href="imagen.gif" />
    <link rel="icon" type="image/vnd.microsoft.icon" href="imagen.ico" /-->
    <!-- Latest compiled and minified CSS -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css"-->

    <!-- Latest compiled and minified JavaScript -->
    <!--script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script-->
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'icono.png' %}"/>
    <link rel="icon" type="image/png" href="{% static 'icono.png' %}" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}" />
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
        ul{
            list-style: none;
        }
        label{
            width: 100px;
        }
    </style>
</head>
<body>
<div class="container">
    <form action="." method="post">
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Alumnos</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Inicio</a></li>
                <li><a href="#">Acerca</a></li>
                <li><a href="#">Contacto</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
        <div class="jumbotron">
            <h2>Modificar</h2>
        </div>
        {% csrf_token %}
        <ul>


            <input id="id" name="id" type="hidden" value="{{ alumno.id }}">
            <li><label for="id_nombres">Nombre:</label><input id="id_nombres" name="nombres" type="text" value="{{ alumno.nombres }}"></li>
            <li><label for="id_apellidop">Ape Paterno:</label> <input id="id_apellidop" name="apellidop" type="text" value="{{ alumno.apellp }}"/></li>
            <li><label for="id_apellidom">Ape Materno:</label> <input id="id_apellidom" name="apellidom" type="text" value="{{ alumno.apellm }}"/></li>
            <li><label for="id_edad">Edad:</label> <input id="id_edad" name="edad" type="text" value="{{ alumno.edad }}"/></li>
            <li><label for="id_carrera">Carrera:</label> <input id="id_carrera" name="carrera" type="text" value="{{ alumno.carrera }}"/></li>
            <input type="submit" value="Modificar"/>
        </ul>
    </form>
</div>

</body>
</html>

apps/inicio/templates/nuevo.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Nuevo</title>
    <!-- Latest compiled and minified CSS -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css"-->

    <!-- Latest compiled and minified JavaScript -->
    <!--script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script-->
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'icono.png' %}"/>
    <link rel="icon" type="image/png" href="{% static 'icono.png' %}" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}" />
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
        ul{
            list-style: none;
        }
        label{
            width: 100px;
        }
    </style>
</head>
<body>
<div class="container">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Alumnos</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Inicio</a></li>
            <li><a href="#">Acerca</a></li>
            <li><a href="#">Contacto</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="jumbotron">
            <h2>Nuevo</h2>
        </div>
    <ul>
    <form action="." method="post">
        {% csrf_token %}



        {{ form.as_ul }}
        <input type="submit" value="Registrar"/>
    </form>
        </ul>
</div>

</body>
</html>